f = open('ai-career-login.html', 'w', encoding='utf-8')

f.write('<!DOCTYPE html>\n')
f.write('<html lang="zh-CN">\n')
f.write('<head>\n')
f.write('<meta charset="UTF-8">\n')
f.write('<meta name="viewport" content="width=device-width,initial-scale=1.0">\n')
f.write('<title>Future Career · AI智能职业规划平台</title>\n')
f.write('<style>\n')

f.write(':root {\n')
f.write('    --blue: #00d4ff;\n')
f.write('    --purple: #a855f7;\n')
f.write('    --bg: #0a061a;\n')
f.write('    --card-bg: rgba(30,20,60,0.6);\n')
f.write('}\n')

f.write('* { margin: 0; padding: 0; box-sizing: border-box; }\n')
f.write('body { min-height: 100vh; background: var(--bg); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; overflow: hidden; }\n')

f.write('.bg { position: fixed; top: 0; left: 0; width: 100%; height: 100%; z-index: 0; }\n')
f.write('#stars { position: absolute; top: 0; left: 0; width: 100%; height: 100%; }\n')

f.write('.decor { position: absolute; background: rgba(0,212,255,0.03); border: 1px solid rgba(0,212,255,0.08); border-radius: 16px; backdrop-filter: blur(10px); }\n')
f.write('.d1 { top: 40px; left: 40px; width: 180px; height: 80px; }\n')
f.write('.d2 { top: 40px; right: 40px; width: 120px; height: 60px; }\n')
f.write('.d3 { bottom: 40px; left: 40px; width: 150px; height: 60px; }\n')
f.write('.d4 { bottom: 40px; right: 40px; width: 200px; height: 80px; }\n')

f.write('.main { position: relative; z-index: 1; display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 40px; }\n')
f.write('.wrap { display: flex; gap: 80px; max-width: 1400px; width: 100%; align-items: center; }\n')

f.write('.left { flex: 1; display: flex; flex-direction: column; align-items: center; position: relative; }\n')
f.write('.brand { position: absolute; top: -60px; left: 0; display: flex; align-items: center; gap: 8px; }\n')
f.write('.brand-title { font-size: 16px; font-weight: 600; color: var(--blue); letter-spacing: 1px; }\n')
f.write('.brand-dot { color: rgba(255,255,255,0.3); font-size: 14px; }\n')
f.write('.brand-sub { font-size: 11px; color: rgba(255,255,255,0.4); }\n')

f.write('.globe-box { margin-bottom: 50px; }\n')
f.write('.globe { width: 280px; height: 280px; }\n')

f.write('.title-area { text-align: center; margin-bottom: 60px; }\n')
f.write('.title { display: flex; gap: 8px; margin-bottom: 15px; justify-content: center; }\n')
f.write('.tc { font-size: 48px; font-weight: bold; background: linear-gradient(135deg, var(--blue), var(--purple)); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; text-shadow: 0 0 40px rgba(0,212,255,0.5); }\n')
f.write('.subtitle { font-size: 14px; color: rgba(255,255,255,0.5); letter-spacing: 12px; }\n')

f.write('.guest-btn { padding: 12px 55px; background: transparent; border: 1px solid rgba(0,212,255,0.5); border-radius: 25px; color: var(--blue); font-size: 14px; cursor: pointer; transition: all 0.3s ease; position: absolute; bottom: -80px; }\n')
f.write('.guest-btn:hover { background: rgba(0,212,255,0.1); border-color: var(--blue); box-shadow: 0 0 30px rgba(0,212,255,0.3); }\n')

f.write('.right { flex: 1; display: flex; justify-content: center; }\n')
f.write('.card { width: 100%; max-width: 420px; background: var(--card-bg); border-radius: 16px; padding: 50px 45px; position: relative; backdrop-filter: blur(20px); border: 1px solid rgba(255,255,255,0.05); }\n')

f.write('.card-border { position: absolute; top: 0; left: 0; right: 0; bottom: 0; pointer-events: none; }\n')
f.write('.cr { position: absolute; width: 40px; height: 40px; border: 1px solid; }\n')
f.write('.cr.tl { top: 12px; left: 12px; border-right: none; border-bottom: none; border-color: var(--blue); box-shadow: 0 0 15px rgba(0,212,255,0.5); }\n')
f.write('.cr.tr { top: 12px; right: 12px; border-left: none; border-bottom: none; border-color: var(--purple); box-shadow: 0 0 15px rgba(168,85,247,0.5); }\n')
f.write('.cr.bl { bottom: 12px; left: 12px; border-right: none; border-top: none; border-color: var(--purple); box-shadow: 0 0 15px rgba(168,85,247,0.5); }\n')
f.write('.cr.br { bottom: 12px; right: 12px; border-left: none; border-top: none; border-color: var(--blue); box-shadow: 0 0 15px rgba(0,212,255,0.5); }\n')

f.write('.edg { position: absolute; height: 1px; left: 55px; right: 55px; background: linear-gradient(90deg, transparent, rgba(0,212,255,0.3), transparent); }\n')
f.write('.edg.top { top: 12px; }\n')
f.write('.edg.bottom { bottom: 12px; background: linear-gradient(90deg, transparent, rgba(168,85,247,0.3), transparent); }\n')
f.write('.edg-v { position: absolute; width: 1px; top: 55px; bottom: 55px; background: linear-gradient(180deg, transparent, rgba(0,212,255,0.3), transparent); }\n')
f.write('.edg-v.left { left: 12px; }\n')
f.write('.edg-v.right { right: 12px; background: linear-gradient(180deg, transparent, rgba(168,85,247,0.3), transparent); }\n')

f.write('.card-header { text-align: center; margin-bottom: 35px; }\n')
f.write('.tabs { display: flex; align-items: center; justify-content: center; gap: 12px; margin-bottom: 20px; }\n')
f.write('.tab { padding: 6px 18px; background: rgba(0,212,255,0.08); border: 1px solid rgba(0,212,255,0.2); border-radius: 15px; font-size: 12px; color: var(--blue); cursor: pointer; display: flex; align-items: center; gap: 6px; }\n')
f.write('.tab:before { content: "◎"; font-size: 8px; opacity: 0.6; }\n')
f.write('.tab.active { background: rgba(0,212,255,0.18); border-color: rgba(0,212,255,0.4); }\n')
f.write('.tab-more { color: rgba(255,255,255,0.3); font-size: 14px; margin-left: 5px; }\n')
f.write('.card-title { font-size: 28px; font-weight: bold; color: #fff; margin-bottom: 8px; }\n')
f.write('.card-sub { font-size: 13px; color: rgba(255,255,255,0.4); }\n')

f.write('.form { display: flex; flex-direction: column; gap: 22px; }\n')
f.write('.input-group { position: relative; }\n')
f.write('.input-wrap { position: relative; background: rgba(255,255,255,0.03); border-radius: 10px; border: 1px solid rgba(255,255,255,0.15); transition: all 0.3s ease; }\n')
f.write('.input-wrap:focus-within { border-color: rgba(0,212,255,0.4); box-shadow: 0 0 20px rgba(0,212,255,0.1); }\n')
f.write('.icon { position: absolute; left: 20px; top: 50%; transform: translateY(-50%); font-size: 18px; color: rgba(255,255,255,0.4); z-index: 1; }\n')
f.write('.inp { width: 100%; padding: 16px 16px 16px 55px; background: transparent; border: none; border-radius: 10px; color: #fff; font-size: 15px; outline: none; }\n')
f.write('.inp::placeholder { color: rgba(255,255,255,0.3); }\n')
f.write('.forgot { position: absolute; right: 0; bottom: -26px; font-size: 12px; color: rgba(255,255,255,0.5); text-decoration: none; }\n')

f.write('.options { display: flex; justify-content: space-between; align-items: center; margin-top: 8px; }\n')
f.write('.checkbox-label { display: flex; align-items: center; gap: 8px; cursor: pointer; }\n')
f.write('.checkbox-label input { display: none; }\n')
f.write('.checkbox { width: 16px; height: 16px; border: 1px solid rgba(255,255,255,0.3); border-radius: 50%; position: relative; }\n')
f.write('.checkbox-label input:checked + .checkbox { background: rgba(0,212,255,0.2); border-color: var(--blue); }\n')
f.write('.checkbox-label input:checked + .checkbox:after { content: ""; position: absolute; top: 4px; left: 4px; width: 6px; height: 6px; background: var(--blue); border-radius: 50%; }\n')
f.write('.checkbox-text { font-size: 13px; color: rgba(255,255,255,0.5); }\n')
f.write('.quick-guest { padding: 7px 20px; background: rgba(168,85,247,0.15); border: 1px solid rgba(168,85,247,0.3); border-radius: 15px; color: var(--purple); font-size: 12px; cursor: pointer; }\n')

f.write('.login-btn { width: 100%; padding: 17px; margin-top: 5px; background: linear-gradient(135deg, var(--blue), var(--purple)); border: none; border-radius: 10px; color: #fff; font-size: 16px; font-weight: bold; cursor: pointer; letter-spacing: 2px; position: relative; overflow: hidden; }\n')
f.write('.login-btn:hover { transform: translateY(-2px); box-shadow: 0 10px 35px rgba(0,212,255,0.4), 0 10px 35px rgba(168,85,247,0.3); }\n')
f.write('.shine { position: absolute; top: 0; left: -100%; width: 100%; height: 100%; background: linear-gradient(90deg, transparent, rgba(255,255,255,0.3), transparent); animation: shineMove 3s infinite; }\n')
f.write('@keyframes shineMove { 0% { left: -100%; } 50%, 100% { left: 100%; } }\n')

f.write('.divider { display: flex; align-items: center; gap: 15px; margin: 30px 0; }\n')
f.write('.line { flex: 1; height: 1px; background: rgba(255,255,255,0.08); position: relative; }\n')
f.write('.line:after { content: ""; position: absolute; top: 0; left: 0; right: 0; height: 100%; background: linear-gradient(90deg, transparent, rgba(0,212,255,0.3), transparent); }\n')
f.write('.divider-text { font-size: 12px; color: rgba(255,255,255,0.4); }\n')

f.write('.social { display: flex; justify-content: center; gap: 20px; }\n')
f.write('.sbtn { width: 48px; height: 48px; border-radius: 50%; background: rgba(0,0,0,0.3); border: 1px solid rgba(255,255,255,0.1); display: flex; align-items: center; justify-content: center; font-size: 22px; cursor: pointer; }\n')
f.write('.sbtn:hover { background: rgba(0,212,255,0.15); border-color: rgba(0,212,255,0.4); }\n')

f.write('@media (max-width: 1024px) { .wrap { flex-direction: column; gap: 60px; } .brand { position: relative; top: 0; margin-bottom: 30px; } .tc { font-size: 36px; } .subtitle { font-size: 12px; letter-spacing: 8px; } .guest-btn { position: relative; bottom: 0; margin-top: 20px; } .globe { width: 220px; height: 220px; } }\n')

f.write('</style>\n')
f.write('</head>\n')
f.write('<body>\n')

f.write('<div class="bg"><canvas id="stars"></canvas><div class="decor d1"></div><div class="decor d2"></div><div class="decor d3"></div><div class="decor d4"></div></div>\n')

f.write('<div class="main">\n')
f.write('<div class="wrap">\n')

f.write('<div class="left">\n')
f.write('<div class="brand"><span class="brand-title">Future Career</span><span class="brand-dot">·</span><span class="brand-sub">AI智能职业规划平台</span></div>\n')

f.write('<div class="globe-box"><div class="globe">')
f.write('<svg viewBox="0 0 280 280">')
f.write('<defs>')
f.write('<linearGradient id="g1" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" style="stop-color:#00d4ff;stop-opacity:0.8"/><stop offset="100%" style="stop-color:#a855f7;stop-opacity:0.4"/></linearGradient>')
f.write('<radialGradient id="g2" cx="40%" cy="40%" r="60%"><stop offset="0%" style="stop-color:#00d4ff;stop-opacity:0.3"/><stop offset="50%" style="stop-color:#a855f7;stop-opacity:0.15"/><stop offset="100%" style="stop-color:#a855f7;stop-opacity:0"/></radialGradient>')
f.write('<filter id="glow"><feGaussianBlur stdDeviation="3" result="coloredBlur"/><feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge></filter>')
f.write('</defs>')
f.write('<circle cx="140" cy="140" r="95" fill="url(#g2)" filter="url(#glow)"/>')
f.write('<g stroke="url(#g1)" stroke-width="0.6" fill="none" opacity="0.7">')
f.write('<circle cx="140" cy="140" r="35"/><circle cx="140" cy="140" r="55"/><circle cx="140" cy="140" r="75"/><circle cx="140" cy="140" r="90"/>')
f.write('<line x1="45" y1="140" x2="235" y2="140"/><line x1="140" y1="45" x2="140" y2="235"/>')
f.write('<line x1="70" y1="70" x2="210" y2="210"/><line x1="210" y1="70" x2="70" y2="210"/>')
f.write('<line x1="55" y1="105" x2="225" y2="175"/><line x1="225" y1="105" x2="55" y2="175"/>')
f.write('<line x1="105" y1="55" x2="175" y2="225"/><line x1="175" y1="55" x2="105" y2="225"/>')
f.write('</g>')
f.write('<g filter="url(#glow)">')
f.write('<circle cx="140" cy="50" r="4" fill="#00d4ff"><animate attributeName="opacity" values="0.4;1;0.4" dur="2s" repeatCount="indefinite"/><animate attributeName="r" values="3;5;3" dur="2s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="230" cy="140" r="4" fill="#00d4ff"><animate attributeName="opacity" values="0.4;1;0.4" dur="2.3s" repeatCount="indefinite"/><animate attributeName="r" values="3;5;3" dur="2.3s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="140" cy="230" r="4" fill="#00d4ff"><animate attributeName="opacity" values="0.4;1;0.4" dur="2.1s" repeatCount="indefinite"/><animate attributeName="r" values="3;5;3" dur="2.1s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="50" cy="140" r="4" fill="#00d4ff"><animate attributeName="opacity" values="0.4;1;0.4" dur="2.2s" repeatCount="indefinite"/><animate attributeName="r" values="3;5;3" dur="2.2s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="75" cy="75" r="3" fill="#a855f7"><animate attributeName="opacity" values="0.5;1;0.5" dur="1.8s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="205" cy="75" r="3" fill="#a855f7"><animate attributeName="opacity" values="0.5;1;0.5" dur="1.9s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="205" cy="205" r="3" fill="#a855f7"><animate attributeName="opacity" values="0.5;1;0.5" dur="2s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="75" cy="205" r="3" fill="#a855f7"><animate attributeName="opacity" values="0.5;1;0.5" dur="2.1s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="105" cy="105" r="2.5" fill="#00d4ff"><animate attributeName="opacity" values="0.6;1;0.6" dur="2.4s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="175" cy="105" r="2.5" fill="#00d4ff"><animate attributeName="opacity" values="0.6;1;0.6" dur="2.2s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="175" cy="175" r="2.5" fill="#00d4ff"><animate attributeName="opacity" values="0.6;1;0.6" dur="2.3s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="105" cy="175" r="2.5" fill="#00d4ff"><animate attributeName="opacity" values="0.6;1;0.6" dur="2.1s" repeatCount="indefinite"/></circle>')
f.write('<circle cx="140" cy="140" r="7" fill="#00d4ff"><animate attributeName="opacity" values="0.5;1;0.5" dur="1.5s" repeatCount="indefinite"/><animate attributeName="r" values="6;9;6" dur="1.5s" repeatCount="indefinite"/></circle>')
f.write('</g>')
f.write('</svg></div></div>\n')

f.write('<div class="title-area"><div class="title"><span class="tc">AI</span><span class="tc">驱</span><span class="tc">动</span><span class="tc">职</span><span class="tc">业</span><span class="tc">导</span><span class="tc">航</span></div><div class="subtitle">智能匹配 · 精准导航 · 成就未来</div></div>\n')

f.write('<button class="guest-btn" onclick="enterGuest()">游客模式开放预览</button>\n')
f.write('</div>\n')

f.write('<div class="right"><div class="card">')
f.write('<div class="card-border"><div class="cr tl"></div><div class="cr tr"></div><div class="cr bl"></div><div class="cr br"></div><div class="edg top"></div><div class="edg bottom"></div><div class="edg-v left"></div><div class="edg-v right"></div></div>')

f.write('<div class="card-header"><div class="tabs"><span class="tab active">智能工作台登录</span><span class="tab">智能工作台登录</span><span class="tab-more">...</span></div><h2 class="card-title">欢迎回来</h2><p class="card-sub">登录您的智能工作空间</p></div>')

f.write('<form class="form" onsubmit="handleLogin(event)">')
f.write('<div class="input-group"><div class="input-wrap"><span class="icon">👤</span><input type="text" id="username" class="inp" placeholder="账号" required></div></div>')
f.write('<div class="input-group"><div class="input-wrap"><span class="icon">🔒</span><input type="password" id="password" class="inp" placeholder="密码" required></div><a href="#" class="forgot">忘记密码</a></div>')
f.write('<div class="options"><label class="checkbox-label"><input type="checkbox" id="remember"><span class="checkbox"></span><span class="checkbox-text">记住我</span></label><button type="button" class="quick-guest" onclick="enterGuest()">游客预览</button></div>')
f.write('<button type="submit" class="login-btn"><span class="shine"></span>立即登录</button>')
f.write('</form>')

f.write('<div class="divider"><div class="line"></div><span class="divider-text">或使用以下快捷登录</span><div class="line"></div></div>')
f.write('<div class="social"><button class="sbtn" onclick="socialLogin(\'wechat\')">💬</button><button class="sbtn" onclick="socialLogin(\'qq\')">🐧</button><button class="sbtn" onclick="socialLogin(\'email\')">📧</button></div>')

f.write('</div></div>\n')
f.write('</div></div>\n')

f.write('<script>\n')
f.write('const canvas = document.getElementById("stars");\n')
f.write('const ctx = canvas.getContext("2d");\n')
f.write('let stars = [];\n')
f.write('\n')
f.write('function resize() {\n')
f.write('    canvas.width = window.innerWidth;\n')
f.write('    canvas.height = window.innerHeight;\n')
f.write('    initStars();\n')
f.write('}\n')
f.write('\n')
f.write('function initStars() {\n')
f.write('    stars = [];\n')
f.write('    const n = Math.floor((canvas.width * canvas.height) / 3000);\n')
f.write('    for (let i = 0; i < n; i++) {\n')
f.write('        stars.push({\n')
f.write('            x: Math.random() * canvas.width,\n')
f.write('            y: Math.random() * canvas.height,\n')
f.write('            size: Math.random() * 2 + 0.5,\n')
f.write('            brightness: Math.random() * 0.6 + 0.4,\n')
f.write('            twinkleSpeed: Math.random() * 0.02 + 0.005,\n')
f.write('            phase: Math.random() * Math.PI * 2\n')
f.write('        });\n')
f.write('    }\n')
f.write('}\n')
f.write('\n')
f.write('function draw() {\n')
f.write('    ctx.fillStyle = "rgba(10,6,26,0.12)";\n')
f.write('    ctx.fillRect(0, 0, canvas.width, canvas.height);\n')
f.write('    stars.forEach(s => {\n')
f.write('        s.phase += s.twinkleSpeed;\n')
f.write('        const a = s.brightness * (0.3 + Math.sin(s.phase) * 0.7);\n')
f.write('        const gr = ctx.createRadialGradient(s.x, s.y, 0, s.x, s.y, s.size * 12);\n')
f.write('        gr.addColorStop(0, "rgba(255,255,255," + (a * 0.25) + ")");\n')
f.write('        gr.addColorStop(0.3, "rgba(200,220,255," + (a * 0.12) + ")");\n')
f.write('        gr.addColorStop(1, "transparent");\n')
f.write('        ctx.beginPath();\n')
f.write('        ctx.arc(s.x, s.y, s.size * 12, 0, Math.PI * 2);\n')
f.write('        ctx.fillStyle = gr;\n')
f.write('        ctx.fill();\n')
f.write('        ctx.beginPath();\n')
f.write('        ctx.arc(s.x, s.y, s.size, 0, Math.PI * 2);\n')
f.write('        ctx.fillStyle = "rgba(255,255,255," + a + ")";\n')
f.write('        ctx.fill();\n')
f.write('    });\n')
f.write('    stars.forEach((s1, i) => {\n')
f.write('        stars.forEach((s2, j) => {\n')
f.write('            if (i < j) {\n')
f.write('                const dx = s1.x - s2.x;\n')
f.write('                const dy = s1.y - s2.y;\n')
f.write('                const d = Math.sqrt(dx * dx + dy * dy);\n')
f.write('                if (d < 80) {\n')
f.write('                    ctx.beginPath();\n')
f.write('                    ctx.moveTo(s1.x, s1.y);\n')
f.write('                    ctx.lineTo(s2.x, s2.y);\n')
f.write('                    ctx.strokeStyle = "rgba(200,220,255," + ((1 - d / 80) * 0.06) + ")";\n')
f.write('                    ctx.lineWidth = 0.4;\n')
f.write('                    ctx.stroke();\n')
f.write('                }\n')
f.write('            }\n')
f.write('        });\n')
f.write('    });\n')
f.write('    requestAnimationFrame(draw);\n')
f.write('}\n')
f.write('\n')
f.write('resize();\n')
f.write('window.addEventListener("resize", resize);\n')
f.write('draw();\n')
f.write('\n')
f.write('function handleLogin(e) {\n')
f.write('    e.preventDefault();\n')
f.write('    if (document.getElementById("username").value && document.getElementById("password").value) {\n')
f.write('        alert("登录成功");\n')
f.write('        window.location.href = "/";\n')
f.write('    }\n')
f.write('}\n')
f.write('\n')
f.write('function enterGuest() {\n')
f.write('    alert("进入游客模式");\n')
f.write('    window.location.href = "/";\n')
f.write('}\n')
f.write('\n')
f.write('function socialLogin(t) {\n')
f.write('    const n = { wechat: "微信", qq: "QQ", email: "邮箱" };\n')
f.write('    alert("跳转" + n[t] + "登录");\n')
f.write('}\n')
f.write('</script>\n')

f.write('</body>\n')
f.write('</html>\n')

f.close()
print('Done!')